### ISSUE TITLE
Saving a new canned response

### ISSUE THREAD

**Issue by alve89** [mkoch227/Mods-for-HESK#172]
The new canned response can't be saved because the title-input is not applied. So after clicking "save" you get the message that the canned response can't be saved because it needs a title - and then the title field is empty.
It works fine with canned tickets.

Might this be caused by the inputs displayed placeholder "Title <span style="? See attachment.

![bildschirmfoto 2015-03-17 um 11 46 17](https://cloud.githubusercontent.com/assets/11487054/6685557/585ed8a4-cc9b-11e4-9db0-ae9eff144602.png)

**Comment by mkoch227** [comment]
I'm unable to reproduce this when using the demo site (http://mods-for-hesk.mkochcs.com/demo). What language is your helpdesk currently translated in? What happens if you set the language to English? It looks like something in your code is causing the input tag to be closed too early (look under the "title" textbox)

**Comment by alve89** [comment]
You’re right, it seems to depend on the language. My site’s running in German, if I set the language to English, it works. How can I solve this problem?



Mit freundlichen Grüßen / Yours sincerely
Stefan Herzog

**Comment by mkoch227** [comment]
Can you email me your language folder for German? (you can send it to mkoch227 [at] gmail [dot] com)

**Comment by alve89** [comment]
See inbox.

**Comment by mkoch227** [comment]
I think I see the issue:

`$hesklang['saved_title']        = 'Titel <span style="color: #565656;">(max. 50 Zeichen)</span>';`

Since the ghost text in the textbox isn't escaped in any way, your `<span>` tag is causing the input to be closed prematurely. Remove the span tag for now and everything should work fine. I'll make a note to have the characters escaped in the next version

**Comment by alve89** [comment]
Great, it’s working fine now. Thank you!


Mit freundlichen Grüßen / Yours sincerely
Stefan Herzog

**Comment by mkoch227** [comment]
Excellent. By the way, would you be willing to let me post your German translation on the Mods for HESK website for others to download? It's completely optional.

**Comment by alve89** [comment]
I already thought to "publish“ it on your site - but it’s not completely finished. I’ll send you the final version.

**Comment by mkoch227** [comment]
Okay that's fine. Thanks!
