### ISSUE TITLE
Improve Statuses UI

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#209]
- [x] Cleanup the UI
- [x] Instead of "key" values, allow the user to click on the name of the status to change it for each language.
    - "Key" values will be auto-generated and placed into a database table, which contains the following columns:
        - Status ID
        - Language Code
        - Text
- [x] Sorting
    - [x] Allow alphabetical
    - [x] Or user-defined
- [x] Update pages that pull from `Key` to use the Xref table instead
- Default status for actions will stay as-is

**Comment by PeopleInside** [comment]
WoW, i hope can be possible in future create custom statues and make available with different language.

If for example i activate two language.. so i will able to set the correct name for the two different language.

**Comment by mkoch227** [comment]
Migrated to JIRA as [MFH-5]

**Comment by bastiaanc** [comment]
It would be great if the statuses  can be alphabetical :-)

**Comment by PeopleInside** [comment]
+1 @bastiaanc

**Comment by mkoch227** [comment]
@bastiaanc , @PeopleInside your wish is my command. I'll add in the option to sort statuses alphabetically or via a user-defined order (similar to how categories will have this functionality in 2.4.0 as well)

**Comment by bastiaanc** [comment]
:-) Awesome
Go Mike  +1

**Comment by PeopleInside** [comment]
Ohm sorry.. my +1 is wrong.. it wants means different thinks i have read bad here.
For me is not priority the order of the status but I don't like for create status or for edit a status you see and can edit wait_reply and not In attesa risposta staff.. so user will see "in attesa risposta staff" that is the text I want edit not wait_reply.

Is not easy also add new status as I don't know what to do "Chiave Key Lingua" I don't understand.

But possibility to order status alphabetically can be useful for some one.
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/8654668/32935cd2-298c-11e5-96c2-ee976f2bbd8e.png)

**Comment by PeopleInside** [comment]
Will be good can decide the status by editing what is in the green circle and in red circle insert English text.. I don't understand how is possible to create or edit statues in different language. I think is not user friendly. Not easy to understand.

For example if i want edit "In Lavorazione" text how can i do? is not clear. Also i want have English string for user who use English interface and i want customize also the English string.

**Comment by bastiaanc** [comment]
Not sure if this was already asked before, but is there a way to show the statuses as the labels in this system? (Bootstrap?) Just a "utopia" thought :-)

**Comment by mkoch227** [comment]
Do you mean something like this? (ignore the pencil icons :stuck_out_tongue_closed_eyes: )

![2015-07-20 07_25_50-help desk](https://cloud.githubusercontent.com/assets/333430/8774881/e4d3a860-2eb0-11e5-8bcf-4f8c23e2f403.png)

**Comment by PeopleInside** [comment]
Nice maybe but..
there is other few problem.

For example, i use the ticket system in two language: my native language Italian and the English language.

So i need to have the status of ticket in English and in Italian so if I need customize the status text i should be able to do fo all active languages enabled in my ticket system.

So "New" i can decide to edit in "New in queue for support" but also i need translate the status for the Italian status.

So maybe pencil is good but should allow in some way to translate status for all active language.

Also where is Add new is no possibile define the label because you can't edit Add new, there is no label field only text color. Language Key who i continue to not understand what is.. if i create a new status what i should insert in the Language key? Why there is Wait_reply this is no user friendly.. what is this "_" tha space? Language Key is not the status seen by the user?!.

For example if I want edit in_progress text showed to the user what i have to do to change the in_progress Language key with "wait_for_staff"? Is not clear to me, no user friendly.

Is not possibile edit status or create custom status on mod of hesk? If yes i cannot understand how works add new and why existing statuses are "on_progress" and not "On progress".. and if i edit something how to edit for italian language too.

For now i have done all of this by editing Italian and English language file but this cannot done from Hesk, Mod of Hesk but must be done via FTP.

Will be great maybe can do this from the Admin side.

**Comment by mkoch227** [comment]
@PeopleInside the changes **are not** complete yet.

**Comment by PeopleInside** [comment]
Ok ^_^

**Comment by mkoch227** [comment]
Just a little update on this.  Below is how the new statuses page will look:
![Imgur](http://i.imgur.com/VDBvtFyh.png)

As you can see, it now looks very similar to other pages (such as manage categories).  If you click the pencil icon, a modal will appear.  This modal will allow you to edit the text for each language (currently I only have English installed on my dev instance), as well as the usual properties on the right side. This should make entering translations **much easier** than before :grinning:.
![Imgur](http://i.imgur.com/qrPRFzy.png)

Let me know what you all think!

**Comment by PeopleInside** [comment]
Hi @mkoch227 it looks like great!

I love it :D

**Comment by bastiaanc** [comment]
Like it :-)
![11027450_10200745492637540_1496207651764690552_n](https://cloud.githubusercontent.com/assets/9219295/8937521/5d6a56c6-3559-11e5-95f1-e9e86c642e74.jpg)
