### ISSUE TITLE
Empty HTML Emails In German

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#224]
1- HTML is on
2- German Language is selected
3- Template "Forgot Password" and "Closed Ticket" are not displaying anything when these are sent
4- The emails will come in but will only have a subject but no content at all
5- In German it will work if "HTML" is off (plain text)
6- Three Ticket Systems show this behavior

**Comment by mkoch227** [comment]
It appears that the HTML-formatted version is lost when trying to automatically add link tags to links in the template.  The link generated when set to German has random whitespace (http :// localhost/admin/password.php h=...), instead of being altogether, which may be the issue. I'll need to look into **why** the whitespace is appearing, since it makes no sense to me without digging deeper.

If you try another language (such as Dutch), does this issue occur?

**Comment by bastiaanc** [comment]
Not in Dutch and not in English this problem occurs. Only in German

**Comment by mkoch227** [comment]
Ok, thanks. I'll investigate further in a little bit. I've been quite busy lately :laughing:

**Comment by mkoch227** [comment]
Ok I figured it out. The templates are saved in **ANSI** format, instead of **UTF-8 without BOM** (byte order mark).  I'm working on converting them now, and will be re-uploaded to the Mods for HESK website in a little bit.

**Comment by mkoch227** [comment]
Ok the fixed de-DE translation is up on the website. If you can download and test it, that would be great.
