### ISSUE TITLE
error in knownledge section of the admin

### ISSUE THREAD

**Issue by leroymcqy** [mkoch227/Mods-for-HESK#236]
when you go to the knowledge section the images isn't showing.

 src="../img/fa-folder-open its missing some things. specially closing (") and what file type. its not in the img folder either. 

also: <i class="fa fa-folder-open style=" color:orange;font-size:17px"="" id="icon_objTreeMenu_1_node_1"></i> idk why it shows like this but it does. 

```php
require(HESK_PATH . 'inc/treemenu/TreeMenu.php');
  $icon         = HESK_PATH . 'img/folder.gif';
  *$expandedIcon = '"fa-folder-open" style="color:orange;font-size:17px"';*
  $menu         = new HTML_TreeMenu();
```

its something with this code tho.

**Comment by mkoch227** [comment]
There shouldn't be any images trying to be displayed, as Mods for HESK uses FontAwesome for all font icons (so all icons should be `<i class="fa fa-folder-open"></i>` for the `folder-open` icon).  I just did a quick search through the repo, and there aren't any `<img` tags except for  "loading.gif", which is included in HESK.  

The only reason I can think of as to why the images weren't loading would be due to the FontAwesome CDN being offline for a short while. If you still are having issues and are using Chrome, can you open the developer tools (F12) and see if any errors are displayed? You can safely ignore missing `.map` files as those aren't included in production environments.

**Comment by leroymcqy** [comment]
It was <I> tag I meant. 
It doesn't seem to close properly. It doesn't show end quote before style

**Comment by mkoch227** [comment]
Ah, ok I see it now. On my browser it still properly renders the icon; however the styling isn't applied (which makes sense since the " is misaligned)

![screen shot 2015-05-10 at 6 57 39 pm](https://cloud.githubusercontent.com/assets/333430/7556616/9ed2821a-f746-11e4-90f4-b63a15b3199c.png)

**Comment by leroymcqy** [comment]
It renders just not closing the tags right. 
Any way to fix it?

**Comment by mkoch227** [comment]
See https://github.com/mkoch227/Mods-for-HESK/commit/a13fe410cf6bb8b5b1af9326137220e7460808a6 for what I did to fix it.
