### ISSUE TITLE
SQL query when update to 2.3.0

### ISSUE THREAD

**Issue by bmsitk** [mkoch227/Mods-for-HESK#368]
Installation fails with error "Could not execute query: UPDATE `hesk_statuses` SET `Key` = `ShortNameContentKey`. MySQL said: Unknown column 'ShortNameContentKey' in 'field list' "

The problem is single quote marks in `ShortNameContentKey`. The query runs if double quote marks used "ShortNameContentKey".

**Comment by mkoch227** [comment]
Hmm... I've never seen an issue like this before.  What version of MySQL are you using? Also, since you wrapped the column name in double quotes, did the keys transfer over properly?

**Comment by bmsitk** [comment]
MySQL Database – version 5.0.91
keys transferred over properly when I used double quotes in the query.
I run into this problem in MS SQL all the time but first time in MySQL. 

Can I edit the query in the code?

**Comment by mkoch227** [comment]
> Can I edit the query in the code?

If you want to edit your own version, go ahead that's fine. However, please do not submit a pull request with the change, because it looks like your MySQL instance has [`ANSI_QUOTES`](https://dev.mysql.com/doc/refman/5.0/en/sql-mode.html#sqlmode_ansi_quotes) turned on which allows you to reference column names in double quotes.  When ANSI_QUOTES is off, double quotes (`"`) are treated exactly the same as single quotes (`'`), so while your MySQL will use the column's value, others will set the ``` `Key` ``` to the literal string "ShortNameContentKey", causing issues. Another option is to try dropping the back ticks altogether, as I doubt MySQL will add `ShortNameContentKey` as a reserved word anytime soon.

**Comment by bmsitk** [comment]
Can you point me to the location in the code?
Thank you.

**Comment by mkoch227** [comment]
https://github.com/mkoch227/Mods-for-HESK/blob/master/install/mods-for-hesk/sql/installSql.php#L455

**Comment by bmsitk** [comment]
Thank you very much.
