### ISSUE TITLE
Knowledgebase problem - can't see added files

### ISSUE THREAD

**Issue by kinatv83** [mkoch227/Mods-for-HESK#405]
Hi,
I added files to my knolwedgebase and it's ok. But when i try open that files i have error : This file has been deleted from the server and is no longer available for download. I cheked my directories on my web server and i saw that added files are in main directory of hesk not in attachements directory.
Can You help me with thist?

**Comment by mkoch227** [comment]
Can you post a screenshot of the "Knowledgebase attachments folder" setting displaying which folder the attachments should be stored in?

**Comment by kinatv83** [comment]
Here you are
![image](https://cloud.githubusercontent.com/assets/15378255/10844935/1f67cfda-7f04-11e5-929e-4744637e6671.png)

**Comment by bastiaanc** [comment]
Since I updated MFH Version 2.4.0 this also disappeared for me.
 #275: Added option to define a separate folder for knowledgebase attachments
I have one folder now "attachments-kb"
When I re-upload the attachments all is working. Somehow with the update (2.4.0) all the links were broken to the documents that were sitting in the original folder "attachments"

**Comment by mkoch227** [comment]
Issue fixed and will be released in 2.6.0.  If you want to apply the fix on your current installation, add the line at `https://github.com/mkoch227/Mods-for-HESK/commit/ee9718f44eff5ef6447e134e04179026437be42f` to your `mange_knowledgebase.php` file.

**Comment by bastiaanc** [comment]
This still won't work for me :-(

**Comment by mkoch227** [comment]
What exactly isn't working? I am able to upload attachments for a KB article to a separate folder for knowledgebase attachments and then download them both on the customer and staff side.  You **will** need to migrate any KB attachments from the old folder to the new one as Mods for HESK is unable to do so automatically.

**Comment by bastiaanc** [comment]
The folder for the knowledge base is now: "attachments-kb"
Before it was linked to "attachments". When I change it back to "attachments" the links are broken. Since the folder attachments is really full and the attachments are renamed it is an enormous task to just find the attachments that were originally attached.

**Comment by mkoch227** [comment]
I've updated `download_attachment.php` to look at both the designated knowledgebase attachments folder as well as the ticket attachments folder in case an attachment hasn't moved to the kb folder.  I will also *try* to add a page to help migrate KB attachments to the new folder; however I am not going to put it in the installer as many web hosts lock down file move permissions on PHP.

This temporary solution should work in the meantime though.

**Comment by bastiaanc** [comment]
Thanks Mike !
