### ISSUE TITLE
"Notify Customers When" Second Checkbox Not Saving

### ISSUE THREAD

**Issue by t-m-b** [mkoch227/Mods-for-HESK#456]
Hi,
I added another person as staff.
Changed respective persmissions individually.
Then changed permission by choosing admin template.
It ticked all checkboxes.
I saved the user.
After saving several checkboxes are not checked for the person.
Thanks for looking into this.
Kind regards,
t-m-b

**Comment by t-m-b** [comment]
This shows the problem live.
http://www.screencast.com/t/8jwnUyY1EAye

**Comment by t-m-b** [comment]
Another setting, that does not stick and unchecks itself.
![checkbox](https://cloud.githubusercontent.com/assets/16400752/12178069/caf9f066-b56f-11e5-8c40-f4a8fd1027fe.jpg)

**Comment by mkoch227** [comment]
The first issue is due to choosing the "Admin" template. Since features/categories are not saved for admins, the page doesn't properly know how to set the checkboxes. That will be fixed when the permissions systems is overhauled.

The second issue (the checkbox in settings not being saved) will be fixed in 2.5.3.
